# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20151122_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, default=0, help_text=b'(Optional) # of minutes allowed to complete worksheet'),
        ),
    ]
