# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20170325_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
