# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_questionresponse_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestion',
            name='auto_grade',
            field=models.BooleanField(default=True, help_text=b'UNCHECK if this requires an external reader/grader'),
        ),
    ]
