# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20170218_1026'),
        ('questions', '0016_questionresponse_grade_request_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.TextField(blank=True, null=True)),
                ('extra_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='optionquestion',
            name='content_area',
            field=models.ForeignKey(blank=True, help_text=b'Related module (section) for this question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Section'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='content_area',
            field=models.ForeignKey(blank=True, help_text=b'Related module (section) for this question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Section'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Section'),
        ),
        migrations.AddField(
            model_name='optionquestion',
            name='extra_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.ExtraInfo'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='extra_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.ExtraInfo'),
        ),
    ]
