# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20170410_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='short_description',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optionquestion',
            name='content_area',
            field=models.ForeignKey(blank=True, help_text=b'(optional) Choose a related module (section) for this question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Section'),
        ),
        migrations.AlterField(
            model_name='optionquestion',
            name='extra_info',
            field=models.ForeignKey(blank=True, help_text=b'(optional) Choose to add rubric and/or additional instructions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.ExtraInfo'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='content_area',
            field=models.ForeignKey(blank=True, help_text=b'(optional) Choose a related module (section) for this question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Section'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='extra_info',
            field=models.ForeignKey(blank=True, help_text=b'(optional) Choose to add rubric and/or additional instructions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.ExtraInfo'),
        ),
    ]
