# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20170410_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionquestion',
            name='min_correct',
            field=models.PositiveIntegerField(default=1, help_text=b'Indicate minimum points to consider as correct.'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='min_correct',
            field=models.PositiveIntegerField(default=1, help_text=b'Indicate minimum points to consider as correct.'),
        ),
    ]
