# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20170416_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='extra_help',
            field=models.TextField(blank=True, null=True),
        ),
    ]
