# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_extrainfo_extra_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='feedback',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
