# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-15 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_questionresponse_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='pretest_subject',
            field=models.CharField(blank=True, help_text=b'Associate this worksheet to: math, science, socialstudies, writing. Only set this for worksheets that are used as pretests.', max_length=24, null=True),
        ),
    ]
