# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2022-09-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_questionset_pretest_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='display_extra_content',
            field=models.TextField(default=b''),
        ),
    ]
