# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2022-09-12 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_questionset_display_extra_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='display_extra_content',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
