# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20160419_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggvuser',
            name='last_deactivation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
