# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20170211_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggvuser',
            name='survey_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
