# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20170410_2312'),
        ('core', '0047_ggvuser_survey_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCourseGoogleDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_file_id', models.CharField(max_length=512)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
