# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20170410_2312'),
        ('core', '0048_tempcoursegoogledb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcoursegoogledb',
            name='course',
        ),
        migrations.AddField(
            model_name='tempcoursegoogledb',
            name='ggv_org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='google_db', to='courses.GGVOrganization'),
            preserve_default=False,
        ),
    ]
