# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20170721_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
