# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-24 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20171007_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='mark_type',
            field=models.CharField(choices=[(b'remember', b'Review,Revisa'), (b'todo', b'Need to Finish,Acabar'), (b'started', b'Start,Comienza'), (b'completed', b'Completed,Completado'), (b'proficient', b'Proficient,Competente'), (b'question', b'Question,Pregunta'), (b'none', b'None,Borrar')], default=b'none', max_length=32),
        ),
    ]
