# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-01 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_ggvuser_deactivation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggvuser',
            name='deactivation_pending',
            field=models.BooleanField(default=False),
        ),
    ]
