# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20170719_1205'),
        ('core', '0056_ggvaccountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggvaccountrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
