# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20180128_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ggvaccountrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
