# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20180128_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggvaccountrequest',
            name='user_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
