# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_ggvaccountrequest_user_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
