# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_sitepage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemessage',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='sitemessage',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='sitemessage',
            name='show',
            field=models.BooleanField(default=True, help_text=b'Display message?'),
        ),
    ]
