# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slidestacks', '0002_auto_20150318_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidestack',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Section'),
        ),
    ]
