# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_ggvorganization_quota_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ggvorganization',
            name='business_contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
