# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20161002_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_courses', to='courses.CourseTag'),
        ),
    ]
