# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20170131_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='ggv_organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_tags', to='courses.GGVOrganization'),
        ),
    ]
