# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20170131_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='taggedcourse',
            options={'ordering': ['course']},
        ),
        migrations.AlterField(
            model_name='taggedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='courses.Course'),
        ),
    ]
