# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170210_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetag',
            name='instructor_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='manager_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='student_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ggvorganization',
            name='instructor_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ggvorganization',
            name='manager_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ggvorganization',
            name='student_quota',
            field=models.IntegerField(default=0),
        ),
    ]
