# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_coursegrader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ggv_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_courses', to='courses.GGVOrganization'),
        ),
    ]
