# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20170719_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chat_room_name',
            field=models.CharField(blank=True, help_text=b'name of chat room to associated with the course. Relates to a Rocket Chat department name.', max_length=255, null=True),
        ),
    ]
