# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-14 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_chat_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='chat_room_name',
            field=models.CharField(blank=True, help_text=b'name of chat room to associate with the course. Relates to a Rocket Chat department name.', max_length=255, null=True),
        ),
    ]
