# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20170211_1801'),
        ('pretests', '0003_pretestuserassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='pretestuser',
            name='ggv_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.GGVOrganization'),
        ),
        migrations.AddField(
            model_name='pretestuser',
            name='language_pref',
            field=models.CharField(blank=True, choices=[('english', 'english'), ('spanish', 'spanish')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pretestuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='pretestuser',
            name='program_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
