# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0005_auto_20170220_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestuser',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='pretests.PretestAccount'),
        ),
    ]
