# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20170211_1801'),
        ('pretests', '0006_auto_20170220_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pretestuser',
            name='ggv_org',
        ),
        migrations.AddField(
            model_name='pretestaccount',
            name='ggv_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.GGVOrganization'),
        ),
        migrations.AlterField(
            model_name='pretestuser',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='pretests.PretestAccount'),
        ),
    ]
