# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0007_auto_20170220_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestaccount',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
