# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_questionset_time_limit'),
        ('pretests', '0008_auto_20170220_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretestUserCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('completed_pretest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretest_completions', to='questions.QuestionSet')),
                ('pretestuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretest_user_completions', to='pretests.PretestUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
