# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 00:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pretests', '0010_auto_20170304_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestaccount',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pretestaccount',
            name='tokens_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
