# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0011_auto_20170304_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestuser',
            name='access_token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
