# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0012_auto_20170304_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pretestuser',
            options={'ordering': ['last_name', 'email']},
        ),
    ]
