# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-25 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0014_auto_20170317_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestquestionresponse',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
