# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-01 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0015_pretestquestionresponse_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pretestuser',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='pretestquestionresponse',
            name='grade_request_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pretestusercompletion',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
