# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-09 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0017_pretestuserassignment_pretest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pretestuserassignment',
            name='pretest',
        ),
    ]
