# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-09 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_questionresponse_feedback'),
        ('pretests', '0018_remove_pretestuserassignment_pretest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestuserassignment',
            name='pretest',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionSet'),
            preserve_default=False,
        ),
    ]
