# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0019_pretestuserassignment_pretest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pretestuserassignment',
            name='lesson',
        ),
    ]
