# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-12 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_questionresponse_feedback'),
        ('pretests', '0020_remove_pretestuserassignment_lesson'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pretestuserassignment',
            unique_together=set([('pretestuser', 'pretest')]),
        ),
    ]
