# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-14 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0021_auto_20170812_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestaccount',
            name='tests_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
