# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_section_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[(b'math', b'math'), (b'science', b'science'), (b'socialstudies', b'socialstudies'), (b'writing', b'writing'), (b'pre_math', b'pre_math'), (b'pre_science', b'pre_science'), (b'pre_socialstudies', b'pre_socialstudies'), (b'pre_writing', b'pre_writing'), (b'default', b'default')], max_length=32),
        ),
    ]
